### ISSUE TITLE
Unable to exchange the session id for an access token with Okta Auth SDK

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-ionic-auth-example#1]
authClient.signIn works fine, but authClient.token does not. Relevant code:

```typescript
import { Component, ViewChild } from '@angular/core';
import { NavController } from 'ionic-angular';
import { OAuthService } from 'angular-oauth2-oidc';
import { TabsPage } from '../tabs/tabs';
declare let OktaAuth: any;

@Component({
  selector: 'page-login',
  templateUrl: 'login.html'
})
export class LoginPage {
  @ViewChild('email') email: any;
  private username: string;
  private password: string;
  private error: string;

  constructor(private navCtrl: NavController, private oauthService: OAuthService) {
    this.oauthService.clientId = 'RqjWvpvWO77qMGgDfukY';
    this.oauthService.issuer = 'https://dev-158606.oktapreview.com';
  }

  login(): void {
    this.oauthService.createAndSaveNonce().then(nonce => {
      const authClient = new OktaAuth({
        clientId: this.oauthService.clientId,
        redirectUri: window.location.origin,
        url: this.oauthService.issuer
      });
      authClient.signIn({
        username: this.username,
        password: this.password
      }).then((response) => {
        console.log('response', response);
        console.log('window.location.origin', window.location.origin);
        if (response.status === 'SUCCESS') {
          // it makes it to here when running in iOS Simulator, then times out after a minute
          authClient.token.getWithoutPrompt({
            nonce: nonce,
            responseType: ['id_token', 'token'],
            sessionToken: response.sessionToken,
          })
            .then((tokens) => {
              console.log('tokens', tokens);
              // oauthService.processIdToken doesn't set an access token
              // set it manually so oauthService.authorizationHeader() works
              localStorage.setItem('access_token', tokens[1].accessToken);
              this.oauthService.processIdToken(tokens[0].idToken, tokens[1].accessToken);
              this.navCtrl.push(TabsPage);
            })
            .catch(error => console.error(error));
        } else {
          throw new Error('We cannot handle the ' + response.status + ' status');
        }
      }).fail((error) => {
        console.error(error);
        this.error = error.message;
      });
    });
  }

  ionViewDidLoad(): void {
    setTimeout(() => {
      this.email.setFocus();
    }, 500);
  }
}
```

To reproduce, you'll need to first install cordova and ionic:

```
npm install -g cordova ionic
```

Then run `npm install` on this application, followed by `ionic serve`. You should be able to login with demo@okta.com/Password1. 

To reproduce this bug, make sure you have Xcode installed, then run:

```
ionic cordova emulate ios
```

This will launch iOS Simulator. When you try to login, it will hang. You can use Safari's Develop > Simulator to debug and see the browser console. After about a minute, you'll see the following error:

![screen shot 2017-06-07 at 11 10 45 am](https://user-images.githubusercontent.com/17892/26891330-e1dc9f06-4b71-11e7-9180-09055b4e0b31.png)

If you'd like to setup your own OIDC app to test this against, you'll need to configure it as follows:

![screen shot 2017-06-07 at 11 12 07 am](https://user-images.githubusercontent.com/17892/26891388-1629d832-4b72-11e7-8d58-9fac5605d94d.png)

**Comment by mraible** [comment]
This might be caused by the fact that Ionic sends an origin header of `file://` when running in Simulator or on a device. I tried setting the redirectUri to `file://` when running in the browser and I received the following error.

![screen shot 2017-06-07 at 11 29 10 am](https://user-images.githubusercontent.com/17892/26892157-a13559f4-4b74-11e7-832e-04b8f94849b0.png)

According to https://forum.ionicframework.com/t/origin-header-of-file-sent-for-http-requests/77413/2, this is caused by versions of Tomcat less than 8.0.37.

**Comment by mraible** [comment]
Solved by using Cordova's in-app browser to redirect to Okta for login.

**Comment by AlexTazetdinov** [comment]
Did someone find any other solution?

**Comment by mraible** [comment]
@AlexTazetdinov Here's a solution that doesn't use Cordova's InApp browser: https://github.com/oktadeveloper/generator-jhipster-ionic/issues/28
