### ISSUE TITLE
Can you add Facebook authentication to this?

### ISSUE THREAD

**Issue by kdbeall** [oktadeveloper/okta-ionic-auth-example#7]
Reading [https://developer.okta.com/authentication-guide/social-login/facebook](this) it seems that
you add a widget to your configuration?

```
idps: [
  {type: 'FACEBOOK', id: '$Your_FB_IDP_ID_Here'}
]
```

Is this possible with ionic?

**Comment by mraible** [comment]
This example uses Okta's hosted widget, so you'd have to customize your widget in your account. You should be able to do this under Settings > Customer Sign In. If you don't see this option, please send an email to developers@okta.com to get it added to your account.
