### ISSUE TITLE
Not able to login from http://localhost:8100/ionic-lab

### ISSUE THREAD

**Issue by writetobegin** [oktadeveloper/okta-ionic-auth-example#8]
I used your repo and added my clientID from OKTA.
If I run http://localhost:8100/ I am able to log in and it works fine.
But If I check mobile view using url  http://localhost:8100/ionic-lab this will display android, ios and windows UI. Attached screenshot..
![screen shot 2018-05-16 at 12 15 33 am](https://user-images.githubusercontent.com/22753871/40102112-79577128-589e-11e8-8efe-aeaf8553b3f4.png)

If I clicked login with OKTA button no action happend
Repo:
https://github.com/writetobegin/okta-ionic-auth-example

**Comment by mraible** [comment]
Do you get an error on Okta or nothing happens at all? The only thing I can think of is you'll need to whitelist the redirect URI, otherwise it should work.

**Comment by writetobegin** [comment]
Looks like a problem  in following line
  const browser = window.cordova.InAppBrowser.open(oauthUrl, '_blank',
          'location=no,clearsessioncache=yes,clearcache=yes');
browser value comming as undefined.

**Comment by mraible** [comment]
Ahh, I know what's happening. Ionic thinks you're running in native mode, so it tries to use the InAppBrowser, which is only available when you're running on the device. This same thing happens when you run in Chrome and enable the device toolbar.

**Comment by writetobegin** [comment]
After I deployed in IonicFramework and viewed from "Ionic view app"(currently available in Android OS only) I have the same issue.
My app Id:
78f53226
![image](https://user-images.githubusercontent.com/22753871/40335566-3ae00890-5d19-11e8-95cc-4dbb7aa9023f.png)

**Comment by writetobegin** [comment]
Will try and let you know .
Appreciate your response.

**Comment by writetobegin** [comment]
I am not able to test now. I will retest again.
Now I will close this issue.
